# Generated by Django 2.0.13 on 2021-11-25 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('button_type', models.SmallIntegerField(choices=[(1, 'STUPID'), (2, 'FAT'), (3, 'DUMP')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('button_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_calls', to='chat.ButtonType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_button_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
